// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkolvdetonkcjtylodol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rb2x2ZGV0b25rY2p0eWxvZG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzMwOTYsImV4cCI6MjA3MTkwOTA5Nn0.zU-ukMihAgzOAOSDjWkqZTAryS4-8zA6kHdXubSvsGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});